import { Send } from 'lucide-react';
import type { SectionDefinition } from '../types';

export const composerSection: SectionDefinition = {
  id: 'composer',
  label: 'Composer',
  icon: Send,
  description: 'Chat input box appearance',
  groups: [
    {
      title: 'Surface',
      controls: [
        {
          type: 'color',
          key: 'composer.backgroundColor',
          label: 'Background Color',
          description: 'Background color (hex/rgb/rgba). Opacity controlled separately.',
        },
        {
          type: 'slider',
          key: 'composer.backgroundOpacity',
          label: 'Background Opacity',
          description: 'Background opacity when not focused',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
        },
        {
          type: 'slider',
          key: 'composer.backgroundOpacityFocused',
          label: 'Focused Opacity',
          description: 'Background opacity when the input is focused',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
        },
        {
          type: 'slider',
          key: 'composer.backdropBlurPx',
          label: 'Backdrop Blur',
          description: 'Backdrop blur behind the composer (frosted glass effect)',
          min: 0,
          max: 20,
          step: 1,
          suffix: 'px',
        },
        {
          type: 'slider',
          key: 'composer.radiusPx',
          label: 'Corner Radius',
          description: 'Roundness of the composer container',
          min: 0,
          max: 32,
          step: 1,
          suffix: 'px',
        },
      ],
    },
    {
      title: 'Send Button',
      controls: [
        {
          type: 'select',
          key: 'composer.sendButtonType',
          label: 'Type',
          description: 'Show a label button, an icon-only button, or hide it entirely',
          options: [
            { value: 'label', label: 'Label' },
            { value: 'icon', label: 'Icon' },
            { value: 'hidden', label: 'Hidden' },
          ],
        },
        {
          type: 'color',
          key: 'composer.sendButtonBackgroundColor',
          label: 'Background Color',
          description: 'Button background color (hex/rgb/rgba). Opacity controlled separately.',
          showWhen: { key: 'composer.sendButtonType', value: 'label' },
        },
        {
          type: 'color',
          key: 'composer.sendButtonBackgroundColor',
          label: 'Background Color',
          description: 'Button background color (hex/rgb/rgba). Opacity controlled separately.',
          showWhen: { key: 'composer.sendButtonType', value: 'icon' },
        },
        {
          type: 'slider',
          key: 'composer.sendButtonBackgroundOpacity',
          label: 'Background Opacity',
          description: 'Background opacity when enabled',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
          showWhen: { key: 'composer.sendButtonType', value: 'label' },
        },
        {
          type: 'slider',
          key: 'composer.sendButtonBackgroundOpacity',
          label: 'Background Opacity',
          description: 'Background opacity when enabled',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
          showWhen: { key: 'composer.sendButtonType', value: 'icon' },
        },
        {
          type: 'slider',
          key: 'composer.sendButtonBackgroundOpacityDisabled',
          label: 'Disabled Background Opacity',
          description: 'Background opacity when disabled',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
          showWhen: { key: 'composer.sendButtonType', value: 'label' },
        },
        {
          type: 'slider',
          key: 'composer.sendButtonBackgroundOpacityDisabled',
          label: 'Disabled Background Opacity',
          description: 'Background opacity when disabled',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
          showWhen: { key: 'composer.sendButtonType', value: 'icon' },
        },
        {
          type: 'color',
          key: 'composer.sendButtonTextColor',
          label: 'Text/Icon Color',
          description: 'Color for the send label/icon',
          showWhen: { key: 'composer.sendButtonType', value: 'label' },
        },
        {
          type: 'color',
          key: 'composer.sendButtonTextColor',
          label: 'Text/Icon Color',
          description: 'Color for the send label/icon',
          showWhen: { key: 'composer.sendButtonType', value: 'icon' },
        },
        {
          type: 'slider',
          key: 'composer.sendButtonTextOpacityDisabled',
          label: 'Disabled Text/Icon Opacity',
          description: 'Opacity for text/icon when disabled',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
          showWhen: { key: 'composer.sendButtonType', value: 'label' },
        },
        {
          type: 'slider',
          key: 'composer.sendButtonTextOpacityDisabled',
          label: 'Disabled Text/Icon Opacity',
          description: 'Opacity for text/icon when disabled',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
          showWhen: { key: 'composer.sendButtonType', value: 'icon' },
        },
        {
          type: 'slider',
          key: 'composer.sendButtonRadiusPx',
          label: 'Corner Radius',
          description: 'Roundness of the send button',
          min: 0,
          max: 24,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'composer.sendButtonType', value: 'label' },
        },
        {
          type: 'slider',
          key: 'composer.sendButtonRadiusPx',
          label: 'Corner Radius',
          description: 'Roundness of the send button',
          min: 0,
          max: 24,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'composer.sendButtonType', value: 'icon' },
        },
        {
          type: 'svg-upload',
          key: 'composer.sendButtonIconSvg',
          label: 'Custom Icon SVG',
          description: 'Paste raw SVG code or drag an .svg file here.',
          showWhen: { key: 'composer.sendButtonType', value: 'icon' },
        },
      ],
    },
    {
      title: 'Border',
      controls: [
        {
          type: 'slider',
          key: 'composer.borderWidthPx',
          label: 'Border Width',
          description: 'Border thickness',
          min: 0,
          max: 4,
          step: 1,
          suffix: 'px',
        },
        {
          type: 'color',
          key: 'composer.borderColor',
          label: 'Border Color',
          description: 'Border color (hex/rgb/rgba). Opacity controlled separately.',
        },
        {
          type: 'slider',
          key: 'composer.borderOpacity',
          label: 'Border Opacity',
          description: 'Border opacity when not focused',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
        },
        {
          type: 'slider',
          key: 'composer.borderOpacityFocused',
          label: 'Focused Opacity',
          description: 'Border opacity when focused',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
        },
      ],
    },
    {
      title: 'Shadow',
      controls: [
        {
          type: 'switch',
          key: 'composer.shadowEnabled',
          label: 'Drop Shadow',
          description: 'Adds a CSS box-shadow to the composer',
        },
        {
          type: 'text',
          key: 'composer.shadowCss',
          label: 'Shadow CSS',
          description: 'Raw CSS box-shadow value (e.g. 0 -10px 30px rgba(0,0,0,0.35))',
          showWhen: { key: 'composer.shadowEnabled', value: true },
        },
      ],
    },
  ],
};

