import { LayoutGrid, Image, Palette } from 'lucide-react';
import type { SectionDefinition } from '../types';

export const headerSection: SectionDefinition = {
  id: 'header',
  label: 'Header',
  icon: LayoutGrid,
  description: 'Top bar layout and branding',
  groups: [
    {
      title: 'Layout',
      controls: [
        {
          type: 'select',
          key: 'header.displayMode',
          label: 'Display Mode',
          description: 'Normal header, or hidden until you hover near the top edge',
          options: [
            { value: 'normal', label: 'Normal' },
            { value: 'hover-reveal', label: 'Hover Reveal (desktop)' },
          ],
        },
        {
          type: 'text',
          key: 'header.hoverTabText',
          label: 'Hover Tab Text',
          description: 'Small tab label that appears on hover when header is hidden',
          showWhen: { key: 'header.displayMode', value: 'hover-reveal' },
        },
        {
          type: 'slider',
          key: 'header.hoverRevealZoneHeightPx',
          label: 'Hover Zone Height',
          description: 'How close to the top edge before the tab appears',
          min: 4,
          max: 120,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'header.displayMode', value: 'hover-reveal' },
        },
        {
          type: 'slider',
          key: 'header.hoverTabFontSizePx',
          label: 'Tab Font Size',
          description: 'Font size of the hover tab label',
          min: 8,
          max: 24,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'header.displayMode', value: 'hover-reveal' },
        },
        {
          type: 'select',
          key: 'header.widthMode',
          label: 'Width Mode',
          description: 'Match chat container width or span full page',
          options: [
            { value: 'match-chat', label: 'Match Chat Width' },
            { value: 'full', label: 'Full Width' },
          ],
        },
        {
          type: 'slider',
          key: 'header.heightPx',
          label: 'Height',
          description: 'Header height in pixels',
          min: 30,
          max: 96,
          step: 1,
          suffix: 'px',
        },
        {
          type: 'slider',
          key: 'header.paddingX',
          label: 'Horizontal Padding',
          description: 'Inner left/right padding',
          min: 0,
          max: 32,
          step: 1,
          suffix: 'px',
        },
        {
          type: 'slider',
          key: 'header.backdropBlurPx',
          label: 'Backdrop Blur',
          description: 'Frosted glass blur behind the header',
          min: 0,
          max: 20,
          step: 1,
          suffix: 'px',
        },
        {
          type: 'switch',
          key: 'header.roundedBottom',
          label: 'Rounded Bottom',
          description: 'Round bottom corners',
        },
        {
          type: 'slider',
          key: 'header.radiusPx',
          label: 'Corner Radius',
          description: 'Bottom corner radius',
          min: 0,
          max: 24,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'header.roundedBottom', value: true },
        },
      ],
    },
    {
      title: 'Background',
      icon: Image,
      controls: [
        {
          type: 'color',
          key: 'header.backgroundColor',
          label: 'Color',
          description: 'Header background color (hex)',
        },
        {
          type: 'slider',
          key: 'header.backgroundOpacity',
          label: 'Opacity',
          description: 'Background opacity',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
        },
      ],
    },
    {
      title: 'Border',
      controls: [
        {
          type: 'switch',
          key: 'header.borderBottom',
          label: 'Show Border',
          description: 'Show border (bottom always; sides when rounded + chat-width mode)',
        },
        {
          type: 'color',
          key: 'header.borderColor',
          label: 'Border Color',
          description: 'Divider color',
          showWhen: { key: 'header.borderBottom', value: true },
        },
        {
          type: 'slider',
          key: 'header.borderOpacity',
          label: 'Border Opacity',
          description: 'Divider opacity',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
          showWhen: { key: 'header.borderBottom', value: true },
        },
        {
          type: 'slider',
          key: 'header.borderWidthPx',
          label: 'Border Width',
          description: 'Divider thickness',
          min: 0,
          max: 4,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'header.borderBottom', value: true },
        },
      ],
    },
    {
      title: 'Shadow',
      controls: [
        {
          type: 'switch',
          key: 'header.shadowEnabled',
          label: 'Drop Shadow',
          description: 'Adds a CSS box-shadow to the header',
        },
        {
          type: 'slider',
          key: 'header.shadowOffsetXPx',
          label: 'Offset X',
          description: 'Horizontal shadow offset',
          min: -40,
          max: 40,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'header.shadowEnabled', value: true },
        },
        {
          type: 'slider',
          key: 'header.shadowOffsetYPx',
          label: 'Offset Y',
          description: 'Vertical shadow offset',
          min: -40,
          max: 40,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'header.shadowEnabled', value: true },
        },
        {
          type: 'slider',
          key: 'header.shadowBlurPx',
          label: 'Blur',
          description: 'Shadow blur radius',
          min: 0,
          max: 80,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'header.shadowEnabled', value: true },
        },
        {
          type: 'slider',
          key: 'header.shadowSpreadPx',
          label: 'Spread',
          description: 'Shadow spread radius',
          min: -40,
          max: 40,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'header.shadowEnabled', value: true },
        },
        {
          type: 'color',
          key: 'header.shadowColor',
          label: 'Color',
          description: 'Shadow color',
          showWhen: { key: 'header.shadowEnabled', value: true },
        },
        {
          type: 'slider',
          key: 'header.shadowOpacity',
          label: 'Opacity',
          description: 'Shadow opacity',
          min: 0,
          max: 100,
          step: 5,
          suffix: '%',
          showWhen: { key: 'header.shadowEnabled', value: true },
        },
      ],
    },
    {
      title: 'Branding',
      icon: Palette,
      controls: [
        {
          type: 'switch',
          key: 'header.showLogo',
          label: 'Show Logo',
          description: 'Display logo image',
        },
        {
          type: 'text',
          key: 'header.logoUrl',
          label: 'Logo URL',
          description: 'Path or URL to logo image',
          showWhen: { key: 'header.showLogo', value: true },
        },
        {
          type: 'slider',
          key: 'header.logoHeightPx',
          label: 'Logo Height',
          description: 'Logo height in pixels',
          min: 16,
          max: 64,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'header.showLogo', value: true },
        },
        {
          type: 'slider',
          key: 'header.logoMaxWidthPx',
          label: 'Logo Max Width',
          description: 'Prevent huge logos from stretching layout',
          min: 60,
          max: 320,
          step: 10,
          suffix: 'px',
          showWhen: { key: 'header.showLogo', value: true },
        },
        {
          type: 'switch',
          key: 'header.showTitle',
          label: 'Show Title',
          description: 'Display text title',
        },
        {
          type: 'text',
          key: 'header.titleText',
          label: 'Title Text',
          description: 'Header title string',
          showWhen: { key: 'header.showTitle', value: true },
        },
        {
          type: 'color',
          key: 'header.titleColor',
          label: 'Title Color',
          description: 'Title text color',
          showWhen: { key: 'header.showTitle', value: true },
        },
        {
          type: 'slider',
          key: 'header.titleSizePx',
          label: 'Title Size',
          description: 'Title font size',
          min: 10,
          max: 24,
          step: 1,
          suffix: 'px',
          showWhen: { key: 'header.showTitle', value: true },
        },
        {
          type: 'select',
          key: 'header.settingsButtonVariant',
          label: 'Settings Button',
          description: 'Button style variant',
          options: [
            { value: 'secondary', label: 'Secondary' },
            { value: 'outline', label: 'Outline' },
            { value: 'ghost', label: 'Ghost' },
            { value: 'default', label: 'Default' },
            { value: 'destructive', label: 'Destructive' },
          ],
        },
      ],
    },
  ],
};

